title: 'Regulär: 11,00 €'
content: 'Regulär: 11,00 € (Ermäßigungen & Unterstützer:innenpreise bei Buchung möglich)'
updated_by: b1a43fd3-c865-4122-b6cc-50cfa81a1985
updated_at: 1617986292
blueprint: preisprofil
