title: 'VVK 18,- € | Abendkasse 20,- € | VVK (U30) 13,- € | Abendkasse (U30) 15,- € | Familienprogramm (15-19 Uhr) 10,- €'
updated_by: b1a43fd3-c865-4122-b6cc-50cfa81a1985
updated_at: 1722771581
blueprint: preisprofil
