title: Production
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: 'Titel / Title'
          listable: hidden
          input_type: text
          antlers: false
      -
        handle: subtitle
        field:
          input_type: text
          antlers: false
          display: 'Untertitel / Subtitle'
          type: text
          icon: text
          listable: hidden
      -
        handle: additional_info
        field:
          input_type: text
          antlers: false
          display: 'Zusatsinformation / Additional info'
          type: text
          icon: text
          listable: hidden
      -
        handle: overview
        field:
          display: 'Überblick / Overview'
          type: section
          icon: section
          listable: hidden
      -
        handle: categories
        field:
          type: terms
          taxonomies:
            - kategorien
          display: 'Kategorien / Categories'
          mode: select
          listable: hidden
          width: 50
      -
        handle: ticket_price
        field:
          type: terms
          taxonomies:
            - preisprofil
          display: 'Preisprofil / Ticket price'
          mode: select
          width: 50
          listable: hidden
      -
        handle: first_last_performance
        field:
          mode: range
          time_enabled: false
          time_required: false
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Erste-letzte Vorstellung / First-Last Performance'
          type: date
          icon: date
          instructions: Von...Bis
          listable: hidden
          width: 33
      -
        handle: premiere_urauffuehrung
        field:
          mode: single
          time_enabled: true
          time_required: true
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Premiere / Uraufführung'
          type: date
          icon: date
          listable: hidden
          width: 33
          instructions: 'Erste Vorstellung'
      -
        handle: perf_duration
        field:
          input_type: text
          antlers: false
          display: 'Duration / Dauer'
          type: text
          icon: text
          instructions: 'z.B. 1 Stunde, ohne Pause.'
          listable: hidden
          width: 33
      -
        handle: ticket-link_event_global
        field:
          input_type: url
          antlers: false
          display: 'Ticket-Link Eventgruppe / Ticket Link All Performances'
          type: text
          icon: text
          listable: hidden
      -
        handle: performances
        field:
          display: 'Veranstaltungen / Performances'
          type: section
          icon: section
          listable: hidden
      -
        handle: dates
        field:
          collapse: false
          sets:
            info:
              display: Info
              fields:
                -
                  handle: credits
                  field:
                    fields:
                      -
                        handle: rolle_role
                        field:
                          mode: select
                          collections:
                            - rollen
                          display: 'Rolle / Role'
                          type: entries
                          icon: entries
                          width: 50
                          listable: hidden
                      -
                        handle: artist
                        field:
                          mode: select
                          collections:
                            - kuenstler_innen
                          display: 'Künstler / Artist'
                          type: entries
                          icon: entries
                          listable: hidden
                    mode: table
                    reorderable: true
                    display: Credits
                    type: grid
                    icon: grid
                    listable: hidden
          display: Dates
          type: replicator
          icon: replicator
          listable: hidden
      -
        handle: credits
        field:
          fields:
            -
              handle: rolle
              field:
                mode: select
                collections:
                  - rollen
                display: Rolle
                type: entries
                icon: entries
                width: 50
                listable: hidden
            -
              handle: kuenstler_innen
              field:
                mode: select
                collections:
                  - kuenstler_innen
                display: 'Künstler*innen'
                type: entries
                icon: entries
                listable: hidden
                width: 50
          mode: stacked
          add_row: 'Neue Rolle eintragen'
          reorderable: true
          display: Credits
          type: grid
          icon: grid
          listable: hidden
      -
        handle: page_content
        field:
          display: 'Seite / Content'
          type: section
          icon: section
          listable: hidden
      -
        import: page_builder
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      -
        handle: date
        field:
          type: date
          validate:
            - required
          listable: hidden
          mode: single
          time_enabled: true
          time_required: true
          earliest_date: '1900-01-01'
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: 'Datum / Date'
      -
        handle: ausverkauft
        field:
          display: Ausverkauft
          type: toggle
          icon: toggle
          listable: hidden
  seo:
    display: SEO
    fields:
      -
        import: seo
