title: Sonstiges
template: produktionen/show
layout: layout
revisions: false
route: 'produktionen/{slug}'
date: true
sort_dir: asc
date_behavior:
  past: public
  future: private
structure:
  root: false
  max_depth: 2
  tree:
    -
      entry: d451b25b-da2c-499f-8667-18c07b1abb62
      children:
        -
          entry: 8d40f8df-4fd0-42fb-a00d-eaf57a28665a
        -
          entry: 4bf033c4-e3ff-498c-aa60-9b152e3b2b09
